name: Dishlocal Model Training

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  run-training-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ================================================================
      # SỬA LỖI TRIỆT ĐỂ BẰNG CÁCH THÊM PPA
      # ================================================================
      - name: Install build dependencies
        run: |
          # Thêm PPA deadsnakes để apt có thể tìm thấy python3.10-dev
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          # Bây giờ lệnh cài đặt sẽ thành công
          sudo apt-get install -y build-essential python3.10-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Production Training Script
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        run: python prod/train.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_PROD_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_PROD_SERVICE_KEY }}

      - name: Run Development Training Script
        if: github.ref == 'refs/heads/develop'
        run: python dev/train.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_DEV_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_DEV_SERVICE_KEY }}